### ISSUE TITLE
TODO list of /rank page.

### ISSUE THREAD

**Issue by bunnyxt** [bunnyxt/tdd-frontend#40]
不爽，不想憋英文了，直说吧，

现在基本是做完了，目前想展示的内容能展示的内容都有了，颜色系统也用上了，移动端桌面端看上去都挺好的了，rank页面看的人目前可以说是最多，接下来要做的几个事情这里列一下：

- [ ] 点击封面跳转到B站的提示要再明显一点，鼠标移动上去，图片上显示一个遮罩层，粉红色B站色+视频播放按钮，提示可以跳转到B站
- [ ] 鼠标移动到视频标题上，跳出来一个popover，调用video api，展示视频简单情况，就类似video detail drawer，不包括action bar，包括laststat，这个做好之后可以用在很多别的地方
- [ ] 鼠标移动到UP主上，跳出来一个popover，调用member api，展示UP主简单情况，这个没啥内容很简单的，不包括action bar，包括三个last，这个做好之后可以用在很多别的地方
- [ ] 在选期和列表中间添加介绍，包括：
  - [ ] 这是第几期，从什么时候到什么时候（overview api里有）
  - [ ] 颜色系统是啥意思，介绍一下四个separator
  - [ ] 更新频率一小时一次，每周归档一次，与周刊时间同步
  - [ ] 其他的有关这一期的信息，需要后端给新的接口
  - [ ] 以上信息不超过1/3屏幕高度，用好折叠隐藏
- [ ] 发现错误，点击报告反馈，点一下，输入问题就好，联系方式和名字可选；整合server酱，直接推送给我
